- id: cfn-inline-lambda-linter
  name: CloudFormation Inline Lambda Linter
  entry: cfn_lambda_lint lint
  language: python
  types: [yaml]
  files: \.ya?ml$
  description: Lints inline Python code in CloudFormation YAML templates.
  args: []  # Default args can be empty or set to some initial values
  pass_filenames: true